### ISSUE TITLE
Invalid byte sequence in US-ASCII (ArgumentError)

### ISSUE THREAD

**Issue by albabosh** [hadley/data-movies#3]
I get "02-import.rb:36:in `match': invalid byte sequence in US-ASCII (ArgumentError)", what sould I do with it?

**Comment by kmmbvnr** [comment]
```
02-import.rb:36:in `match': invalid byte sequence in UTF-8 (ArgumentError)
    from 02-import.rb:36:in `block (2 levels) in import_times'
    from 02-import.rb:33:in `each_line'
    from 02-import.rb:33:in `block in import_times'
    from /usr/lib/ruby/vendor_ruby/sqlite3/database.rb:500:in `transaction'
    from 02-import.rb:32:in `import_times'
    from 02-import.rb:117:in `<main>'

```

yeah, same error

**Comment by brycepg** [comment]
The `.list` files are in `iso-8859-1` format, but newer ruby versions ruby defaults to to UTF-8, If I understand correctly(I don't use ruby much).

To mitigate this, you need to explicitly state the external encoding for each `File.new`:
    
    File.new("...") needs to be
    File.new("...", external_encoding=> 'iso-8859-1')
`

Applying this regex in vim would work: 

    %s/\(File\.new(".\{-}"\)\().*\)/\1, :external_encoding => 'iso-8859-1'\2/

I've also attached a git patch for the file.
[invalid-byte-fix.patch.txt](https://github.com/hadley/data-movies/files/584617/invalid-byte-fix.patch.txt)

**Comment by brycepg** [comment]
The author has definitely abandoned this project. It's written for an old version of ruby, and I think the imdb data format may have changed a little.

One of the pull requests fixes this issue as well as some other issues. To use his fixes run

```
 git clone https://github.com/andreykurenkov/data-movies -b update-2016
 cd data-movies
 bash run-all.sh
```

This will checkout the branch of his(`update-2016`) from his repo and run the script he made which downloads everything, sets up the sqlite schema, and runs the ruby scripts.

For Ubuntu 16.04 I needed to install `sqlite3` as well as the gem `arrayfields` (`gem install arrayfields`). You can use `sqlitebrowser` to verify the output database at `movies.sqlite3`.

It looks like all the data has been moved to the `Movies` table. The `Genre` table is not functional (missing foreign key)
